name: PrivateGames
version: '${project.version}'
main: me.notlewx.privategames.PrivateGames
soft-dependencies: [ BedWars1058, PlaceholderAPI, BedWars2023, BedWarsProxy]
commands:
  pg:
    description: Enables the private games if you are in a party
    aliases:
      - privategame
      - private
      - pgame
